server:
  port: ${PORT:8081}

spring:
  application:
    name: payment-integration-service


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payment_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  web:
    error:
      include-message: always

provider:
  stripe:
    base-url: ${PROVIDER_STRIPE_BASE_URL:http://localhost:8082}
#  paypal:
#    base-url: http://localhost:8083

internal:
  api:
    key: ${INTERNAL_API_KEY:dev-internal-key}
