server:
  port: ${PORT:8081}
  error:
    include-message: always

spring:
  application:
    name: payment-integration-service


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

provider:
  stripe:
    base-url: ${PROVIDER_STRIPE_BASE_URL:http://localhost:8082}
#  paypal:
#    base-url: http://localhost:8083

internal:
  api:
    key: ${INTERNAL_API_KEY:dev-internal-key}
